# generated by datamodel-codegen:
#   filename:  open.json (local PDP)
#   timestamp: 2024-04-09T15:36:45+00:00

from __future__ import annotations

from typing import TYPE_CHECKING, Optional

from ..utils.pydantic_version import PYDANTIC_VERSION

if TYPE_CHECKING:
    # The v1 API is what runs under either pydantic major, so type-check against it.
    from pydantic.v1 import BaseModel, Field
elif PYDANTIC_VERSION < (2, 0):
    from pydantic import BaseModel, Field
else:
    from pydantic.v1 import BaseModel, Field


class RoleAssignment(BaseModel):
    user: str = Field(..., description="the user the role is assigned to", title="User")
    role: str = Field(..., description="the role that is assigned", title="Role")
    tenant: str = Field(..., description="the tenant the role is associated with", title="Tenant")
    resource_instance: Optional[str] = Field(
        default=None,
        description="the resource instance the role is associated with",
        title="Resource Instance",
    )
