"""Permit.io SDK: authorization checks and the Permit REST API from Python.

`__all__` lists the package's public names: the ones `from permit import *` binds, and the
ones type checkers treat as re-exported.
"""

import typing as _typing
import warnings as _warnings

from permit.api.models import *  # noqa: F403 - every API model is part of the public surface
from permit.config import PermitConfig
from permit.enforcement.enforcer import Action, Resource, User
from permit.enforcement.interfaces import (
    AssignedRole,
    AuthorizedUsersResult,
    ResourceInput,
    TenantDetails,
    UserInput,
)
from permit.exceptions import (
    _PERMIT_EXCEPTION_DEPRECATION,
    PermitAlreadyExistsError,
    PermitApiDetailedError,
    PermitApiError,
    PermitConnectionError,
    PermitContextChangeError,
    PermitContextError,
    PermitError,
    PermitNotFoundError,
    PermitValidationError,
    _PermitException,
)
from permit.permit import Permit
from permit.utils.context import Context
from permit.utils.deprecation import _warn_deprecated_name
from permit.utils.pydantic_version import PYDANTIC_VERSION as _PYDANTIC_VERSION

if _typing.TYPE_CHECKING:
    # Deprecated, but still exported for existing callers: __getattr__ below serves it.
    from permit.exceptions import PermitException  # type: ignore[deprecated]

# PermitException is served by __getattr__ below, so a star import binds it with its warning.
# tests/test_fix_permit_exception_deprecation.py fails when a public name is missing.
__all__ = [
    "APIHistoryEventFullRead",
    "APIHistoryEventRead",
    "APIKeyCreate",
    "APIKeyOwnerType",
    "APIKeyRead",
    "APIKeyScopeRead",
    "AVPEngineDecisionLog",
    "AccessRequestApproved",
    "AccessRequestCanceled",
    "AccessRequestCreateDetails",
    "AccessRequestDenied",
    "AccessRequestDetails",
    "AccessRequestRead",
    "AccessRequestReview",
    "AccessRequestReviewDeny",
    "AccessRequestUserCreate",
    "Action",
    "ActionBlockEditable",
    "ActionBlockRead",
    "ActionObj",
    "ActivityDetailsList",
    "ActivityDetailsObject",
    "ActivityDetailsObjectData",
    "ActivityLogEventRead",
    "AddRolePermissions",
    "ApproveMessage",
    "AssignedRole",
    "AttributeBlockEditable",
    "AttributeBlockRead",
    "AttributeType",
    "AuditLogModel",
    "AuditLogObjectsModel",
    "AuditLogReplayRequest",
    "AuditLogReplayResponse",
    "AuditLogSortKey",
    "AuthMechanism",
    "AuthorizedUsersResult",
    "BillingTierType",
    "BulkRoleAssignmentReport",
    "BulkRoleUnAssignmentReport",
    "ConditionSet",
    "ConditionSetCreate",
    "ConditionSetRead",
    "ConditionSetRuleCreate",
    "ConditionSetRuleRead",
    "ConditionSetRuleRemove",
    "ConditionSetType",
    "ConditionSetUpdate",
    "Context",
    "DataGeneratorLibSchemasSchemaOpalDataConditionSetData",
    "DataGeneratorLibSchemasSchemaOpalDataDerivationSettings",
    "DataGeneratorLibSchemasSchemaOpalDataDerivedRole",
    "DataGeneratorLibSchemasSchemaOpalDataDerivedRoleRule",
    "DataGeneratorLibSchemasSchemaOpalDataFullData",
    "DataGeneratorLibSchemasSchemaOpalDataResourceInstanceAttributeData",
    "DataGeneratorLibSchemasSchemaOpalDataResourceTypeData",
    "DataGeneratorLibSchemasSchemaOpalDataRoleData",
    "DataGeneratorLibSchemasSchemaOpalDataTenantData",
    "DataGeneratorLibSchemasSchemaOpalDataUserData",
    "DataSourceConfig",
    "DataSourceEntryWithPollingInterval",
    "DerivedRoleBlockEdit",
    "DerivedRoleBlockRead",
    "DerivedRoleRuleCreate",
    "DerivedRoleRuleDelete",
    "DerivedRoleRuleRead",
    "DetailedAuditLogModel",
    "DummyEngineModel",
    "ElementsConfigCreate",
    "ElementsConfigRead",
    "ElementsConfigRuntimeRead",
    "ElementsConfigUpdate",
    "ElementsPermissionLevel",
    "ElementsRoleRead",
    "ElementsType",
    "ElementsUserCreate",
    "ElementsUserInviteApprove",
    "ElementsUserInviteCreate",
    "ElementsUserInviteRead",
    "ElementsUserInviteUpdate",
    "ElementsUserRoleCreate",
    "ElementsUserRoleRemove",
    "EmailConfigurationCreate",
    "EmailConfigurationRead",
    "EmailMessageKeys",
    "EmailTemplateMessage",
    "EmailTemplateRead",
    "EmailTemplateType",
    "EmailTemplateUpdate",
    "Engine",
    "EnvironmentCopy",
    "EnvironmentCopyConflictStrategy",
    "EnvironmentCopyScope",
    "EnvironmentCopyScopeFilters",
    "EnvironmentCopyTarget",
    "EnvironmentCreate",
    "EnvironmentObj",
    "EnvironmentRead",
    "EnvironmentReadWithEmailConfig",
    "EnvironmentStatistics",
    "EnvironmentStats",
    "EnvironmentUpdate",
    "ErrorCode",
    "ErrorDetails",
    "FailedInvite",
    "GenericEngineDecisionLog",
    "GroupAddRole",
    "GroupAssignUser",
    "GroupAssignment",
    "GroupCreate",
    "GroupRead",
    "GroupReadSchema",
    "HTTPValidationError",
    "HistoricalUsage",
    "HttpMethods",
    "IdentityRead",
    "InviteCreate",
    "InviteRead",
    "InviteStatus",
    "JSONPatchAction",
    "JwksConfig",
    "JwksObj",
    "LimitedPaginatedResultAPIHistoryEventRead",
    "LimitedPaginatedResultActivityLogEventRead",
    "LimitedPaginatedResultAuditLogModel",
    "MailgunEmailConfigurationCreate",
    "MailgunEmailConfigurationRead",
    "MappingRule",
    "MappingRuleUpdate",
    "MemberAccessLevel",
    "MemberAccessObj",
    "Methods",
    "MissingUserPolicy",
    "MonthlyUsage",
    "MultiInviteResult",
    "OPAEngineDecisionLog",
    "OPALClient",
    "OPALCommon",
    "OPALHttpFetcherConfig",
    "OPALUpdateCallback",
    "OPALabels",
    "OPAMetrics",
    "OnboardingStep",
    "OperationApprovalApproved",
    "OperationApprovalCanceled",
    "OperationApprovalCreateDetails",
    "OperationApprovalDenied",
    "OperationApprovalDetails",
    "OperationApprovalList",
    "OperationApprovalRead",
    "OperationApprovalReview",
    "OperationApprovalUserCreate",
    "OrgMemberCreate",
    "OrgMemberRead",
    "OrgMemberReadWithGrants",
    "OrgMemberRemovePermissions",
    "OrgMemberUpdate",
    "OrganizationCreate",
    "OrganizationObj",
    "OrganizationRead",
    "OrganizationReadWithAPIKey",
    "OrganizationStatistics",
    "OrganizationStats",
    "OrganizationUpdate",
    "PDPConfigRead",
    "PDPContext",
    "PDPDataRefreshRequest",
    "PDPDataRefreshResponse",
    "PDPShardMigration",
    "PaginatedResultAPIHistoryEventRead",
    "PaginatedResultAPIKeyRead",
    "PaginatedResultAccessRequestRead",
    "PaginatedResultActivityLogEventRead",
    "PaginatedResultConditionSetRead",
    "PaginatedResultElementsConfigRead",
    "PaginatedResultElementsUserInviteRead",
    "PaginatedResultGroupReadSchema",
    "PaginatedResultOperationApprovalList",
    "PaginatedResultRelationRead",
    "PaginatedResultRelationshipTupleDetailedRead",
    "PaginatedResultRelationshipTupleRead",
    "PaginatedResultResourceInstanceDetailedRead",
    "PaginatedResultResourceInstanceRead",
    "PaginatedResultResourceRead",
    "PaginatedResultResourceRoleRead",
    "PaginatedResultRoleAssignmentDetailedRead",
    "PaginatedResultRoleAssignmentRead",
    "PaginatedResultRoleRead",
    "PaginatedResultTenantRead",
    "PaginatedResultUserRead",
    "PdpConfigObj",
    "PdpValues",
    "Permission",
    "PermissionLevelRoleRead",
    "Permit",
    "PermitAlreadyExistsError",
    "PermitApiDetailedError",
    "PermitApiError",
    "PermitBackendSchemasSchemaDerivedRoleRuleDerivationSettings",
    "PermitBackendSchemasSchemaOpalDataConditionSetData",
    "PermitBackendSchemasSchemaOpalDataDerivationSettings",
    "PermitBackendSchemasSchemaOpalDataDerivedRole",
    "PermitBackendSchemasSchemaOpalDataDerivedRoleRule",
    "PermitBackendSchemasSchemaOpalDataFullData",
    "PermitBackendSchemasSchemaOpalDataResourceInstanceAttributeData",
    "PermitBackendSchemasSchemaOpalDataResourceTypeData",
    "PermitBackendSchemasSchemaOpalDataRoleData",
    "PermitBackendSchemasSchemaOpalDataTenantData",
    "PermitBackendSchemasSchemaOpalDataUserData",
    "PermitConfig",
    "PermitConnectionError",
    "PermitContextChangeError",
    "PermitContextError",
    "PermitError",
    "PermitException",
    "PermitNotFoundError",
    "PermitValidationError",
    "PolicyGuardRuleCreate",
    "PolicyGuardRuleItem",
    "PolicyGuardRuleRead",
    "PolicyGuardScopeAssociate",
    "PolicyGuardScopeCreate",
    "PolicyGuardScopeDetail",
    "PolicyGuardScopeDetailCreate",
    "PolicyGuardScopeRead",
    "PolicyRepoCreate",
    "PolicyRepoRead",
    "PolicyRepoStatus",
    "ProjectCreate",
    "ProjectObj",
    "ProjectRead",
    "ProjectUpdate",
    "ProxyConfigCreate",
    "ProxyConfigRead",
    "ProxyConfigUpdate",
    "RelationBlockRead",
    "RelationCreate",
    "RelationRead",
    "RelationshipTupleBlockRead",
    "RelationshipTupleCreate",
    "RelationshipTupleCreateBulkOperation",
    "RelationshipTupleCreateBulkOperationResult",
    "RelationshipTupleDelete",
    "RelationshipTupleDeleteBulkOperation",
    "RelationshipTupleDeleteBulkOperationResult",
    "RelationshipTupleDetailedRead",
    "RelationshipTupleObj",
    "RelationshipTupleRead",
    "RemoteConfig",
    "RemoveRolePermissions",
    "RequestStatus",
    "RequestType",
    "Resource",
    "ResourceActionCreate",
    "ResourceActionGroupCreate",
    "ResourceActionGroupRead",
    "ResourceActionGroupUpdate",
    "ResourceActionRead",
    "ResourceActionUpdate",
    "ResourceAttributeCreate",
    "ResourceAttributeRead",
    "ResourceAttributeUpdate",
    "ResourceAttributes",
    "ResourceCreate",
    "ResourceInput",
    "ResourceInstanceBlockRead",
    "ResourceInstanceCreate",
    "ResourceInstanceCreateBulkOperation",
    "ResourceInstanceCreateBulkOperationResult",
    "ResourceInstanceDeleteBulkOperation",
    "ResourceInstanceDeleteBulkOperationResult",
    "ResourceInstanceDetailedRead",
    "ResourceInstanceRead",
    "ResourceInstanceUpdate",
    "ResourceRead",
    "ResourceReplace",
    "ResourceRoleCreate",
    "ResourceRoleList",
    "ResourceRoleRead",
    "ResourceRoleUpdate",
    "ResourceTypeObj",
    "ResourceUpdate",
    "RoleAssignmentCreate",
    "RoleAssignmentDetailedRead",
    "RoleAssignmentRead",
    "RoleAssignmentRemove",
    "RoleAssignmentResourceInstance",
    "RoleAssignmentRole",
    "RoleAssignmentTenant",
    "RoleAssignmentUser",
    "RoleBlockEditable",
    "RoleCreate",
    "RoleCreateBulk",
    "RoleCreateBulkOperation",
    "RoleCreateBulkOperationResult",
    "RoleList",
    "RoleRead",
    "RoleUpdate",
    "SMTPEmailConfigurationCreate",
    "SMTPEmailConfigurationRead",
    "SSHAuthData",
    "SSHAuthDataRead",
    "ScopeConfigRead",
    "ScopeConfigSet",
    "SearchOperator",
    "StrippedRelationBlockRead",
    "TaskResultEnvironmentRead",
    "TaskResultPolicyGuardScopeRead",
    "TaskStatus",
    "TenantBlockRead",
    "TenantCreate",
    "TenantCreateBulkOperation",
    "TenantCreateBulkOperationResult",
    "TenantDeleteBulkOperation",
    "TenantDeleteBulkOperationResult",
    "TenantDetails",
    "TenantObj",
    "TenantRead",
    "TenantUpdate",
    "UsageLimits",
    "User",
    "UserCreate",
    "UserCreateBulkOperation",
    "UserCreateBulkOperationResult",
    "UserDeleteBulkOperation",
    "UserDeleteBulkOperationResult",
    "UserInTenant",
    "UserInput",
    "UserInviteStatus",
    "UserObj",
    "UserRead",
    "UserReplaceBulkOperation",
    "UserReplaceBulkOperationResult",
    "UserResourceInstanceRole",
    "UserRole",
    "UserRoleCreate",
    "UserRoleRemove",
    "UserStatus",
    "UserUpdate",
    "ValidationError",
    "WebhookCreateWithElements",
    "WebhookRead",
    "WebhookType",
    "WebhookUpdate",
]

if _PYDANTIC_VERSION < (2, 0):
    # Importing any permit module runs this file first, and only once per process, so this
    # warns once. stacklevel=2 attributes the warning to the code that imported permit (the
    # import machinery's frames are skipped), which Python shows by default when that is
    # __main__.
    _warnings.warn(
        "Support for pydantic 1 is deprecated and will be removed in permit 4.0. "
        "Upgrade to pydantic 2.",
        DeprecationWarning,
        stacklevel=2,
    )


def _getattr(name: str) -> object:
    """Serve the deprecated `PermitException`, with its warning, to code that reads it."""
    if name == "PermitException":
        _warn_deprecated_name(_PERMIT_EXCEPTION_DEPRECATION)
        return _PermitException
    msg = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(msg)


if not _typing.TYPE_CHECKING:
    # The module __getattr__ (PEP 562), out of type checkers' sight like permit.exceptions' one.
    __getattr__ = _getattr
