# Generated by scripts/generate_sync_stubs.py from the async classes. Do not edit;
# run `make generate-sync-stubs` instead.

from typing import Any, Dict, List, Optional, Union
from uuid import UUID

from permit.api.base import BasePermitApi
from permit.api.elements import EmbeddedLoginRequestOutput, UserLoginAsResponse
from permit.api.models import (
    APIKeyRead,
    BulkRoleAssignmentReport,
    BulkRoleUnAssignmentReport,
    ConditionSetCreate,
    ConditionSetRead,
    ConditionSetRuleCreate,
    ConditionSetRuleRead,
    ConditionSetRuleRemove,
    ConditionSetUpdate,
    DerivedRoleRuleCreate,
    DerivedRoleRuleDelete,
    DerivedRoleRuleRead,
    ElementsUserInviteApprove,
    ElementsUserInviteCreate,
    ElementsUserInviteRead,
    EnvironmentCopy,
    EnvironmentCreate,
    EnvironmentRead,
    EnvironmentStats,
    EnvironmentUpdate,
    PaginatedResultElementsUserInviteRead,
    PaginatedResultRelationRead,
    PaginatedResultUserRead,
    PermitBackendSchemasSchemaDerivedRoleRuleDerivationSettings,
    ProjectCreate,
    ProjectRead,
    ProjectUpdate,
    RelationCreate,
    RelationRead,
    RelationshipTupleCreate,
    RelationshipTupleCreateBulkOperationResult,
    RelationshipTupleDelete,
    RelationshipTupleDeleteBulkOperationResult,
    RelationshipTupleRead,
    ResourceActionCreate,
    ResourceActionGroupCreate,
    ResourceActionGroupRead,
    ResourceActionGroupUpdate,
    ResourceActionRead,
    ResourceActionUpdate,
    ResourceAttributeCreate,
    ResourceAttributeRead,
    ResourceAttributeUpdate,
    ResourceCreate,
    ResourceInstanceCreate,
    ResourceInstanceCreateBulkOperationResult,
    ResourceInstanceDeleteBulkOperationResult,
    ResourceInstanceRead,
    ResourceInstanceUpdate,
    ResourceRead,
    ResourceReplace,
    ResourceRoleCreate,
    ResourceRoleRead,
    ResourceRoleUpdate,
    ResourceUpdate,
    RoleAssignmentCreate,
    RoleAssignmentRead,
    RoleAssignmentRemove,
    RoleCreate,
    RoleRead,
    RoleUpdate,
    TenantCreate,
    TenantCreateBulkOperationResult,
    TenantDeleteBulkOperationResult,
    TenantRead,
    TenantUpdate,
    UserCreate,
    UserCreateBulkOperationResult,
    UserDeleteBulkOperationResult,
    UserRead,
    UserReplaceBulkOperationResult,
    UserUpdate,
)
from permit.api.users import _UserSyncInput
from permit.config import PermitConfig
from permit.enforcement.enforcer import Action, CheckQuery, Resource, User
from permit.enforcement.interfaces import AuthorizedUsersResult
from permit.pdp_api.base import BasePdpPermitApi
from permit.pdp_api.models import RoleAssignment
from permit.utils.context import Context, ContextStore
from permit.utils.model_input import ModelInput, ModelListInput

class SyncElementsApi(BasePermitApi):
    def __init__(self, config: PermitConfig): ...
    def login_as(self, user_id: Union[str, UUID], tenant_id: Union[str, UUID]) -> UserLoginAsResponse: ...

class SyncConditionSetRulesApi(BasePermitApi):
    def list(
        self,
        user_set_key: Optional[str] = None,
        permission_key: Optional[str] = None,
        resource_set_key: Optional[str] = None,
        page: int = 1,
        per_page: int = 100,
    ) -> List[ConditionSetRuleRead]:
        """
        Retrieves a list of condition set rule rules.

        Args:
            user_set_key: the key of the userset, if used only rules matching that userset will be fetched.
            permission_key: the key of the permission, formatted as <resource>:<action>.
                if used, only rules granting that permission will be fetched.
            resource_set_key: the key of the resourceset, if used only rules matching that resourceset will be fetched.
            page: The page number to fetch (default: 1).
            per_page: How many items to fetch per page (default: 100).

        Returns:
            an array of condition set rule rules.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def create(self, rule: ModelInput[ConditionSetRuleCreate]) -> List[ConditionSetRuleRead]:
        """
        Creates a new condition set rule.

        Args:
            rule: The condition set rule to create.

        Returns:
            the created condition set rule.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def delete(self, rule: ModelInput[ConditionSetRuleRemove]) -> None:
        """
        Deletes a condition set rule.

        Args:
            rule: The condition set rule to delete.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """

class SyncConditionSetsApi(BasePermitApi):
    def list(self, page: int = 1, per_page: int = 100) -> List[ConditionSetRead]:
        """
        Retrieves a list of condition sets.

        Args:
            page: The page number to fetch (default: 1).
            per_page: How many items to fetch per page (default: 100).

        Returns:
            an array of condition sets.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get(self, condition_set_key: str) -> ConditionSetRead:
        """
        Retrieves a condition set by its key.

        Args:
            condition_set_key: The key of the condition set.

        Returns:
            the condition set.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_key(self, condition_set_key: str) -> ConditionSetRead:
        """
        Retrieves a condition set by its key.
        Alias for the get method.

        Args:
            condition_set_key: The key of the condition set.

        Returns:
            the condition set.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_id(self, condition_set_id: str) -> ConditionSetRead:
        """
        Retrieves a condition set by its ID.
        Alias for the get method.

        Args:
            condition_set_id: The ID of the condition set.

        Returns:
            the condition set.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def create(self, condition_set_data: ModelInput[ConditionSetCreate]) -> ConditionSetRead:
        """
        Creates a new condition set.

        Args:
            condition_set_data: The data for the new condition set.

        Returns:
            the created condition set.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def update(self, condition_set_key: str, condition_set_data: ModelInput[ConditionSetUpdate]) -> ConditionSetRead:
        """
        Updates a condition set.

        Args:
            condition_set_key: The key of the condition set.
            condition_set_data: The updated data for the condition set.

        Returns:
            the updated condition set.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def delete(self, condition_set_key: str) -> None:
        """
        Deletes a condition set.

        Args:
            condition_set_key: The key of the condition set to delete.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """

class SyncDeprecatedApi(BasePermitApi):
    """
    Represents the interface for managing roles.
    """
    def __init__(self, config: PermitConfig): ...
    def get_user(self, user_key: str) -> UserRead: ...
    def get_role(self, role_key: str) -> RoleRead: ...
    def get_tenant(self, tenant_key: str) -> TenantRead: ...
    def get_assigned_roles(
        self, user_key: str, tenant_key: Optional[str], page: int = 1, per_page: int = 100
    ) -> List[RoleAssignmentRead]: ...
    def get_resource(self, resource_key: str) -> ResourceRead: ...
    def list_roles(self, page: int = 1, per_page: int = 100) -> List[RoleRead]: ...
    def sync_user(self, user: Union[UserCreate, Dict[str, Any]]) -> UserRead: ...
    def delete_user(self, user_key: str) -> None: ...
    def list_tenants(self, page: int = 1, per_page: int = 100) -> List[TenantRead]: ...
    def create_tenant(self, tenant: Union[TenantCreate, Dict[str, Any]]) -> TenantRead: ...
    def update_tenant(self, tenant_key: str, tenant: Union[TenantUpdate, Dict[str, Any]]) -> TenantRead: ...
    def delete_tenant(self, tenant_key: str) -> None: ...
    def create_role(self, role: Union[RoleCreate, Dict[str, Any]]) -> RoleRead: ...
    def update_role(self, role_key: str, role: Union[RoleUpdate, Dict[str, Any]]) -> RoleRead: ...
    def assign_role(self, user_key: str, role_key: str, tenant_key: str) -> RoleAssignmentRead: ...
    def unassign_role(self, user_key: str, role_key: str, tenant_key: str) -> None: ...
    def delete_role(self, role_key: str) -> None: ...
    def create_resource(self, resource: Union[ResourceCreate, Dict[str, Any]]) -> ResourceRead: ...
    def update_resource(self, resource_key: str, resource: Union[ResourceUpdate, Dict[str, Any]]) -> ResourceRead: ...
    def delete_resource(self, resource_key: str) -> None: ...
    def elements_login_as(
        self, user_id: Union[str, UUID], tenant_id: Union[str, UUID]
    ) -> EmbeddedLoginRequestOutput: ...

class SyncEnvironmentsApi(BasePermitApi):
    def __init__(self, config: PermitConfig): ...
    def list(self, project_key: str, page: int = 1, per_page: int = 100) -> List[EnvironmentRead]:
        """
        Retrieves a list of environments.

        Args:
            params: The filters and pagination options.

        Returns:
            an array of EnvironmentRead objects representing the listed environments.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get(self, project_key: str, environment_key: str) -> EnvironmentRead:
        """
        Gets an environment by project key and environment key.

        Args:
            project_key: The project key.
            environment_key: The environment key.

        Returns:
            an EnvironmentRead object representing the retrieved environment.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_key(self, project_key: str, environment_key: str) -> EnvironmentRead:
        """
        Gets an environment by project key and environment key.
        Alias for the get method.

        Args:
            project_key: The project key.
            environment_key: The environment key.

        Returns:
            an EnvironmentRead object representing the retrieved environment.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_id(self, project_id: str, environment_id: str) -> EnvironmentRead:
        """
        Gets an environment by project ID and environment ID.
        Alias for the get method.

        Args:
            project_id: The project ID.
            environment_id: The environment ID.

        Returns:
            an EnvironmentRead object representing the retrieved environment.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_stats(self, project_key: str, environment_key: str) -> EnvironmentStats:
        """
        Retrieves statistics and metadata for an environment.

        Args:
            project_key: The project key.
            environment_key: The environment key.

        Returns:
            an EnvironmentStats object representing the statistics data.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_api_key(self, project_key: str, environment_key: str) -> APIKeyRead:
        """
        Retrieves the API key that grants access for an environment.

        Args:
            project_key: The project key.
            environment_key: The environment key.

        Returns:
            an APIKeyRead object containing the API key and its metadata.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def create(self, project_key: str, environment_data: ModelInput[EnvironmentCreate]) -> EnvironmentRead:
        """
        Creates a new environment.

        Args:
            project_key: The project key.
            environment_data: The data for creating the environment.

        Returns:
            an EnvironmentRead object representing the created environment.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def update(
        self, project_key: str, environment_key: str, environment_data: ModelInput[EnvironmentUpdate]
    ) -> EnvironmentRead:
        """
        Updates an existing environment.

        Args:
            project_key: The project key.
            environment_key: The environment key.
            environment_data: The data for updating the environment.

        Returns:
            an EnvironmentRead object representing the updated environment.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def copy(self, project_key: str, environment_key: str, copy_params: ModelInput[EnvironmentCopy]) -> EnvironmentRead:
        """
        Clones data from a source specified environment into a different target environment in the same project.

        Args:
            project_key: The project key.
            environment_key: The environment key.
            copy_params: The parameters for copying the environment.

        Returns:
            an EnvironmentRead object representing the copied environment.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def delete(self, project_key: str, environment_key: str) -> None:
        """
        Deletes an environment.

        Args:
            project_key: The project key.
            environment_key: The environment key.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """

class SyncProjectsApi(BasePermitApi):
    def __init__(self, config: PermitConfig): ...
    def list(self, page: int = 1, per_page: int = 100) -> List[ProjectRead]:
        """
        Retrieves a list of projects.

        Args:
            page: The page number to fetch (default: 1).
            per_page: How many items to fetch per page (default: 100).

        Returns:
            A promise that resolves to an array of projects.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get(self, project_key: str) -> ProjectRead:
        """
        Retrieves a project by its key.

        Args:
            project_key: The key of the project.

        Returns:
            A promise that resolves to the project.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_key(self, project_key: str) -> ProjectRead:
        """
        Retrieves a project by its key.
        Alias for the get method.

        Args:
            project_key: The key of the project.

        Returns:
            A promise that resolves to the project.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_id(self, project_id: str) -> ProjectRead:
        """
        Retrieves a project by its ID.
        Alias for the get method.

        Args:
            project_id: The ID of the project.

        Returns:
            A promise that resolves to the project.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def create(self, project_data: ModelInput[ProjectCreate]) -> ProjectRead:
        """
        Creates a new project.

        Args:
            project_data: The data for the new project.

        Returns:
            A promise that resolves to the created project.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def update(self, project_key: str, project_data: ModelInput[ProjectUpdate]) -> ProjectRead:
        """
        Updates a project.

        Args:
            project_key: The key of the project.
            project_data: The updated data for the project.

        Returns:
            A promise that resolves to the updated project.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def delete(self, project_key: str) -> None:
        """
        Deletes a project.

        Args:
            project_key: The key of the project to delete.

        Returns:
            A promise that resolves when the project is deleted.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """

class SyncRelationshipTuplesApi(BasePermitApi):
    def list(
        self,
        page: int = 1,
        per_page: int = 100,
        subject_key: Optional[str] = None,
        relation_key: Optional[str] = None,
        object_key: Optional[str] = None,
        tenant_key: Optional[str] = None,
    ) -> List[RelationshipTupleRead]:
        """
        Retrieves a list of relationship tuples based on the specified filters.

        Args:
            page: The page number to fetch (default: 1).
            per_page: How many items to fetch per page (default: 100).
            subject_key: if specified, only relationship tuples with this subject will be fetched.
            relation_key: if specified, only relationship tuples with this relation will be fetched.
            object_key: if specified, only relationship tuples with this object will be fetched.
            tenant_key: if specified, only relationship tuples with this tenant will be fetched.

        Returns:
            an array of relationship tuples.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def create(self, tuple_data: ModelInput[RelationshipTupleCreate]) -> RelationshipTupleRead:
        """
        Creates a new relationship tuple, that states that a relationship (of type: relation)
        exists between two resource instances: the subject and the object.

        Args:
            tuple_data: The relationship tuple to create.

        Returns:
            the created relationship tuple.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def delete(self, tuple_data: ModelInput[RelationshipTupleDelete]) -> None:
        """
        Removes a relationship tuple.

        Args:
            tuple_data: The relationship tuple to delete.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def bulk_create(
        self, tuples: ModelListInput[RelationshipTupleCreate]
    ) -> RelationshipTupleCreateBulkOperationResult:
        """
        Creates multiple relationship tuples at once using the provided tuple data.

        Args:
            tuples: The relationship tuples to create.
                Each tuple object is of type RelationshipTupleCreate and is essentially
                a tuple of (subject, relation, object, tenant).

                subject and object are both resource instances, formatted as
                `<resourcetype:instancekey>` strings (e.g: Folder:budget23).
                relation is the name of the relation.
                tenant is the key of the tenant in which to place the relation
                (optional if at least one of subject/object already exists).

                Subject and object must both be resource instances *in the same tenant*!

        Returns:
            the tuples creation result (RelationshipTupleCreateBulkOperationResult)

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def bulk_delete(
        self, tuples: ModelListInput[RelationshipTupleDelete]
    ) -> RelationshipTupleDeleteBulkOperationResult:
        """
        Deletes multiple relationship tuples at once using the provided tuple data.

        Args:
            tuples: The relationship tuples to delete.
                Each tuple object is of type RelationshipTupleDelete and is essentially
                a tuple of (subject, relation, object).

                subject and object are both resource instances, formatted as
                `<resourcetype:instancekey>` strings (e.g: Folder:budget23).
                relation is the name of the relation.

        Returns:
            the tuples deletion result (RelationshipTupleDeleteBulkOperationResult)

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """

class SyncResourceActionGroupsApi(BasePermitApi):
    def list(self, resource_key: str, page: int = 1, per_page: int = 100) -> List[ResourceActionGroupRead]:
        """
        Retrieves a list of action groups.

        Args:
            resource_key: The key of the resource to filter on.
            page: The page number to fetch (default: 1).
            per_page: How many items to fetch per page (default: 100).

        Returns:
            an array of action groups.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get(self, resource_key: str, group_key: str) -> ResourceActionGroupRead:
        """
        Retrieves a action group by its key.

        Args:
            resource_key: The key of the resource the action group belongs to.
            group_key: The key of the action group.

        Returns:
            the action group.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_key(self, resource_key: str, group_key: str) -> ResourceActionGroupRead:
        """
        Retrieves a action group by its key.
        Alias for the get method.

        Args:
            resource_key: The key of the resource the action group belongs to.
            group_key: The key of the action group.

        Returns:
            the action group.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_id(self, resource_id: str, group_id: str) -> ResourceActionGroupRead:
        """
        Retrieves a action group by its ID.
        Alias for the get method.

        Args:
            resource_id: The ID of the resource the action group belongs to.
            group_id: The ID of the action group.

        Returns:
            the action group.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def create(self, resource_key: str, group_data: ModelInput[ResourceActionGroupCreate]) -> ResourceActionGroupRead:
        """
        Creates a new action group.

        Args:
            resource_key: The key of the resource under which the action group should be created.
            group_data: The data for the new action group.

        Returns:
            the created action group.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def update(
        self, resource_key: str, group_key: str, group_data: ModelInput[ResourceActionGroupUpdate]
    ) -> ResourceActionGroupRead:
        """
        Updates an action group.

        Args:
            resource_key: The key of the resource the action group belongs to.
            group_key: The key of the action group.
            group_data: The updated data for the action group.

        Returns:
            the updated action group.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def delete(self, resource_key: str, group_key: str) -> None:
        """
        Deletes a action group.

        Args:
            resource_key: The key of the resource the action group belongs to.
            group_key: The key of the action group to delete.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """

class SyncResourceActionsApi(BasePermitApi):
    def list(self, resource_key: str, page: int = 1, per_page: int = 100) -> List[ResourceActionRead]:
        """
        Retrieves a list of actions.

        Args:
            resource_key: The key of the resource to filter on.
            page: The page number to fetch (default: 1).
            per_page: How many items to fetch per page (default: 100).

        Returns:
            an array of actions.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get(self, resource_key: str, action_key: str) -> ResourceActionRead:
        """
        Retrieves a action by its key.

        Args:
            resource_key: The key of the resource the action belongs to.
            action_key: The key of the action.

        Returns:
            the action.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_key(self, resource_key: str, action_key: str) -> ResourceActionRead:
        """
        Retrieves a action by its key.
        Alias for the get method.

        Args:
            resource_key: The key of the resource the action belongs to.
            action_key: The key of the action.

        Returns:
            the action.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_id(self, resource_id: str, action_id: str) -> ResourceActionRead:
        """
        Retrieves a action by its ID.
        Alias for the get method.

        Args:
            resource_id: The ID of the resource the action belongs to.
            action_id: The ID of the action.

        Returns:
            the action.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def create(self, resource_key: str, action_data: ModelInput[ResourceActionCreate]) -> ResourceActionRead:
        """
        Creates a new action.

        Args:
            resource_key: The key of the resource under which the action should be created.
            action_data: The data for the new action.

        Returns:
            the created action.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def update(
        self, resource_key: str, action_key: str, action_data: ModelInput[ResourceActionUpdate]
    ) -> ResourceActionRead:
        """
        Updates a action.

        Args:
            resource_key: The key of the resource the action belongs to.
            action_key: The key of the action.
            action_data: The updated data for the action.

        Returns:
            the updated action.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def delete(self, resource_key: str, action_key: str) -> None:
        """
        Deletes a action.

        Args:
            resource_key: The key of the resource the action belongs to.
            action_key: The key of the action to delete.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """

class SyncResourceAttributesApi(BasePermitApi):
    def list(self, resource_key: str, page: int = 1, per_page: int = 100) -> List[ResourceAttributeRead]:
        """
        Retrieves a list of attributes.

        Args:
            resource_key: The key of the resource to filter on.
            page: The page number to fetch (default: 1).
            per_page: How many items to fetch per page (default: 100).

        Returns:
            an array of attributes.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get(self, resource_key: str, attribute_key: str) -> ResourceAttributeRead:
        """
        Retrieves a attribute by its key.

        Args:
            resource_key: The key of the resource the attribute belongs to.
            attribute_key: The key of the attribute.

        Returns:
            the attribute.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_key(self, resource_key: str, attribute_key: str) -> ResourceAttributeRead:
        """
        Retrieves a attribute by its key.
        Alias for the get method.

        Args:
            resource_key: The key of the resource the attribute belongs to.
            attribute_key: The key of the attribute.

        Returns:
            the attribute.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_id(self, resource_id: str, attribute_id: str) -> ResourceAttributeRead:
        """
        Retrieves a attribute by its ID.
        Alias for the get method.

        Args:
            resource_id: The ID of the resource the attribute belongs to.
            attribute_id: The ID of the attribute.

        Returns:
            the attribute.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def create(self, resource_key: str, attribute_data: ModelInput[ResourceAttributeCreate]) -> ResourceAttributeRead:
        """
        Creates a new attribute.

        Args:
            resource_key: The key of the resource under which the attribute should be created.
            attribute_data: The data for the new attribute.

        Returns:
            the created attribute.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def update(
        self, resource_key: str, attribute_key: str, attribute_data: ModelInput[ResourceAttributeUpdate]
    ) -> ResourceAttributeRead:
        """
        Updates a attribute.

        Args:
            resource_key: The key of the resource the attribute belongs to.
            attribute_key: The key of the attribute.
            attribute_data: The updated data for the attribute.

        Returns:
            the updated attribute.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def delete(self, resource_key: str, attribute_key: str) -> None:
        """
        Deletes a attribute.

        Args:
            resource_key: The key of the resource the attribute belongs to.
            attribute_key: The key of the attribute to delete.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """

class SyncResourceInstancesApi(BasePermitApi):
    def list(
        self,
        page: int = 1,
        per_page: int = 100,
        tenant_key: Optional[str] = None,
        resource_key: Optional[str] = None,
        detailed_key: Optional[bool] = None,
        search_key: Optional[str] = None,
    ) -> List[ResourceInstanceRead]:
        """
        Retrieves a list of resource instances.

        Args:
            page: The page number to fetch (default: 1).
            per_page: How many items to fetch per page (default: 100).

        Returns:
            an array of resource instances.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get(self, instance_key: str) -> ResourceInstanceRead:
        """
        Retrieves a resource instance by its identity.

        Args:
            instance_key: The resource instance identity. Either `resource_type:instance_key`
                (like Repository:react) or the resource instance uuid. A bare instance key
                is rejected by the API with a 422.

        Returns:
            the resource instance.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_key(self, instance_key: str) -> ResourceInstanceRead:
        """
        Retrieves a resource instance by its identity.
        Alias for the get method.

        Args:
            instance_key: The resource instance identity. Either `resource_type:instance_key`
                (like Repository:react) or the resource instance uuid. A bare instance key
                is rejected by the API with a 422.

        Returns:
            the resource instance.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_id(self, instance_id: str) -> ResourceInstanceRead:
        """
        Retrieves a resource instance by its ID.
        Alias for the get method.

        Args:
            instance_id: The ID of the resource instance.

        Returns:
            the resource instance.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def create(self, instance_data: ModelInput[ResourceInstanceCreate]) -> ResourceInstanceRead:
        """
        Creates a new resource instance.

        Args:
            instance_data: The data for the new resource instance.

        Returns:
            the created resource instance.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def update(self, instance_key: str, instance_data: ModelInput[ResourceInstanceUpdate]) -> ResourceInstanceRead:
        """
        Updates a resource instance.

        Args:
            instance_key: The resource instance identity. Either `resource_type:instance_key`
                (like Repository:react) or the resource instance uuid. A bare instance key
                is rejected by the API with a 422.
            instance_data: The updated data for the resource instance.

        Returns:
            the updated resource instance.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def delete(self, instance_key: str) -> None:
        """
        Deletes a resource instance.

        Args:
            instance_key: The identity of the resource instance to delete. Either `resource_type:instance_key`
                (like Repository:react) or the resource instance uuid. A bare instance key
                is rejected by the API with a 422.

        Returns:
            A promise that resolves when the resource instance is deleted.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def bulk_replace(
        self, resource_instances: ModelListInput[ResourceInstanceCreate]
    ) -> ResourceInstanceCreateBulkOperationResult:
        """
        Creates (and if need replaces) resource instances in bulk.

        If the resource instance exists - replaces it.
        Otherwise creates previously non-existing resource instances.

        Args:
            resource_instances: The resource instances to create/replace.

        Returns:
            the bulk replace report.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def bulk_delete(self, resource_instances: List[str]) -> ResourceInstanceDeleteBulkOperationResult:
        """
        Deletes resource instances in bulk.

        Args:
            resource_instances: The resource instance identities to delete.
            Each identity can be either `resource_type:instance_key` (like Repository:react) or the resource instance uuid.

        Returns:
            the bulk delete report.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """  # noqa: E501

class SyncResourceRelationsApi(BasePermitApi):
    def list(self, resource_key: str, page: int = 1, per_page: int = 100) -> PaginatedResultRelationRead:
        """
        Retrieves a list of outgoing relations originating in a specific (object) resource.

        Args:
            resource_key: The key of the resource to filter on.
            page: The page number to fetch (default: 1).
            per_page: How many items to fetch per page (default: 100).

        Returns:
            a PaginatedResultRelationRead holding the relations in ``.data`` and the
            total number of relations on the resource in ``.total_count``.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get(self, resource_key: str, relation_key: str) -> RelationRead:
        """
        Retrieves a relation by its key.

        Args:
            resource_key: The key of the resource the relation belongs to.
            relation_key: The key of the relation.

        Returns:
            the relation.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_key(self, resource_key: str, relation_key: str) -> RelationRead:
        """
        Retrieves a relation by its key.
        Alias for the get method.

        Args:
            resource_key: The key of the resource the relation belongs to.
            relation_key: The key of the relation.

        Returns:
            the relation.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_id(self, resource_id: str, relation_id: str) -> RelationRead:
        """
        Retrieves a relation by its ID.
        Alias for the get method.

        Args:
            resource_id: The ID of the resource the relation belongs to.
            relation_id: The ID of the relation.

        Returns:
            the relation.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def create(self, resource_key: str, relation_data: ModelInput[RelationCreate]) -> RelationRead:
        """
        Creates a new relation.

        Args:
            resource_key: The key of the resource under which the relation should be created.
            relation_data: The data for the new relation.

        Returns:
            the created relation.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def delete(self, resource_key: str, relation_key: str) -> None:
        """
        Deletes a relation.

        Args:
            resource_key: The key of the resource the relation belongs to.
            relation_key: The key of the relation to delete.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """

class SyncResourceRolesApi(BasePermitApi):
    """
    Represents the interface for managing resource roles.
    """
    def list(self, resource_key: str, page: int = 1, per_page: int = 100) -> List[ResourceRoleRead]:
        """
        Retrieves a list of resource roles.

        Args:
            resource_key: The key of the resource to filter on.
            page: The page number to fetch (default: 1).
            per_page: How many items to fetch per page (default: 100).

        Returns:
            A list of resource roles.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get(self, resource_key: str, role_key: str) -> ResourceRoleRead:
        """
        Retrieves a resource role by its key.

        Args:
            resource_key: The key of the resource the role belongs to.
            role_key: The key of the role.

        Returns:
            The role.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_key(self, resource_key: str, role_key: str) -> ResourceRoleRead:
        """
        Retrieves a resource role by its key.
        Alias for the get method.

        Args:
            resource_key: The key of the resource the role belongs to.
            role_key: The key of the role.

        Returns:
            The role.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_id(self, resource_id: str, role_id: str) -> ResourceRoleRead:
        """
        Retrieves a resource role by its ID.
        Alias for the get method.

        Args:
            resource_id: The ID of the resource the role belongs to.
            role_id: The ID of the role.

        Returns:
            The role.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def create(self, resource_key: str, role_data: ModelInput[ResourceRoleCreate]) -> ResourceRoleRead:
        """
        Creates a new resource role.

        Args:
            resource_key: The key of the resource under which the role should be created.
            role_data: The data for the new role.

        Returns:
            The created role.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def update(self, resource_key: str, role_key: str, role_data: ModelInput[ResourceRoleUpdate]) -> ResourceRoleRead:
        """
        Updates a resource role.

        Args:
            resource_key: The key of the resource the role belongs to.
            role_key: The key of the role.
            role_data: The updated data for the role.

        Returns:
            The updated role.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def delete(self, resource_key: str, role_key: str) -> None:
        """
        Deletes a resource role.

        Args:
            resource_key: The key of the resource the role belongs to.
            role_key: The key of the role to delete.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def assign_permissions(self, resource_key: str, role_key: str, permissions: List[str]) -> ResourceRoleRead:
        """
        Assigns permissions to a resource role.

        Args:
            resource_key: The key of the resource the role belongs to.
            role_key: The key of the role.
            permissions: An array of action keys of `resource_key` (or resource action uuids)
                to be assigned to the role. A resource role is scoped to its own resource, so
                each entry is a bare action key such as `read` - the `<resourceKey:actionKey>`
                form used by top level roles is read as an action key here and is rejected
                with a 404 (MISSING_PERMISSIONS) naming `<resourceKey>:<resourceKey>:<actionKey>`.

        Returns:
            A ResourceRoleRead object representing the updated role.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def remove_permissions(self, resource_key: str, role_key: str, permissions: List[str]) -> ResourceRoleRead:
        """
        Removes permissions from a resource role.

        Args:
            resource_key: The key of the resource the role belongs to.
            role_key: The key of the role.
            permissions: An array of action keys of `resource_key` (or resource action uuids)
                to be removed from the role, in the same bare `read` form `assign_permissions`
                takes.

        Returns:
            A ResourceRoleRead object representing the updated role.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def create_role_derivation(
        self, resource_key: str, role_key: str, derivation_rule: ModelInput[DerivedRoleRuleCreate]
    ) -> DerivedRoleRuleRead:
        """
        Create a conditional derivation from another role.

        The derivation states that users with some other role on a related object will implicitly also be granted this role.

        Args:
            resource_key: The key of the resource the role belongs to.
            role_key: The key of the role.
            derivation_rule: A rule when to derived this role from another related role.

        Returns:
            A DerivedRoleRuleRead object representing the newly created role derivation.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """  # noqa: E501
    def delete_role_derivation(
        self, resource_key: str, role_key: str, derivation_rule: ModelInput[DerivedRoleRuleDelete]
    ) -> None:
        """
        Delete a role derivation.

        Args:
            resource_key: The key of the resource the role belongs to.
            role_key: The key of the role.
            derivation_rule: The details of the derivation rule to delete.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def update_role_derivation_conditions(
        self,
        resource_key: str,
        role_key: str,
        conditions: ModelInput[PermitBackendSchemasSchemaDerivedRoleRuleDerivationSettings],
    ) -> PermitBackendSchemasSchemaDerivedRoleRuleDerivationSettings:
        """
        Update the optional (ABAC) conditions when to derive this role from other roles.

        Args:
            resource_key: The key of the resource the role belongs to.
            role_key: The key of the role.
            conditions: The conditions object.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """

class SyncResourcesApi(BasePermitApi):
    def list(self, page: int = 1, per_page: int = 100) -> List[ResourceRead]:
        """
        Retrieves a list of resources.

        Args:
            page: The page number to fetch (default: 1).
            per_page: How many items to fetch per page (default: 100).

        Returns:
            an array of resources.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get(self, resource_key: str) -> ResourceRead:
        """
        Retrieves a resource by its key.

        Args:
            resource_key: The key of the resource.

        Returns:
            the resource.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_key(self, resource_key: str) -> ResourceRead:
        """
        Retrieves a resource by its key.
        Alias for the get method.

        Args:
            resource_key: The key of the resource.

        Returns:
            the resource.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_id(self, resource_id: str) -> ResourceRead:
        """
        Retrieves a resource by its ID.
        Alias for the get method.

        Args:
            resource_id: The ID of the resource.

        Returns:
            the resource.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def create(self, resource_data: ModelInput[ResourceCreate]) -> ResourceRead:
        """
        Creates a new resource.

        Args:
            resource_data: The data for the new resource.

        Returns:
            the created resource.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def update(self, resource_key: str, resource_data: ModelInput[ResourceUpdate]) -> ResourceRead:
        """
        Updates a resource.

        Args:
            resource_key: The key of the resource.
            resource_data: The updated data for the resource.

        Returns:
            the updated resource.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def replace(self, resource_key: str, resource_data: ModelInput[ResourceReplace]) -> ResourceRead:
        """
        Creates a resource if no such resource exists, otherwise completely replaces the resource in place.

        Args:
            resource_key: The key of the resource.
            resource_data: The updated data for the resource.

        Returns:
            the updated resource.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def delete(self, resource_key: str) -> None:
        """
        Deletes a resource.

        Args:
            resource_key: The key of the resource to delete.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """

class SyncRoleAssignmentsApi(BasePermitApi):
    def list(
        self,
        user_key: Optional[Union[str, List[str]]] = None,
        role_key: Optional[Union[str, List[str]]] = None,
        tenant_key: Optional[Union[str, List[str]]] = None,
        resource_key: Optional[str] = None,
        resource_instance_key: Optional[str] = None,
        page: int = 1,
        per_page: int = 100,
    ) -> List[RoleAssignmentRead]:
        """
        Retrieves a list of role assignments based on the specified filters.

        Args:
            user_key: if specified, only role granted to this user will be fetched.
            role_key: if specified, only assignments of this role will be fetched.
            tenant_key: (for roles) if specified, only role granted within this tenant will be fetched.
            resource_key: (for resource roles) if specified, only roles granted on instances of this resource type will be fetched.
            resource_instance_key: (for resource roles) if specified, only roles granted with this instance as the object will be fetched. The instance identity, either `resource_type:instance_key` (like Repository:react) or the instance uuid; a bare instance key is rejected by the API with a 400.
            page: The page number to fetch (default: 1).
            per_page: How many items to fetch per page (default: 100).

        Returns:
            an array of role assignments.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """  # noqa: E501
    def assign(self, assignment: ModelInput[RoleAssignmentCreate]) -> RoleAssignmentRead:
        """
        Assigns a role to a user in the scope of a given tenant.

        Args:
            assignment: The role assignment details.

        Returns:
            the assigned role.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def unassign(self, unassignment: ModelInput[RoleAssignmentRemove]) -> None:
        """
        Unassigns a role from a user in the scope of a given tenant.

        Args:
            unassignment: The role unassignment details.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def bulk_assign(self, assignments: ModelListInput[RoleAssignmentCreate]) -> BulkRoleAssignmentReport:
        """
        Assigns multiple roles in bulk using the provided role assignments data.
        Each role assignment is a tuple of (user, role, tenant).

        Args:
            assignments: The role assignments to be performed in bulk.

        Returns:
            the bulk assignment report.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def bulk_unassign(self, unassignments: ModelListInput[RoleAssignmentRemove]) -> BulkRoleUnAssignmentReport:
        """
        Removes multiple role assignments in bulk using the provided unassignment data.
        Each role to unassign is a tuple of (user, role, tenant).

        Args:
            unassignments: The role unassignments to be performed in bulk.

        Returns:
            the bulk unassignment report.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """

class SyncRolesApi(BasePermitApi):
    """
    Represents the interface for managing roles.
    """
    def list(self, page: int = 1, per_page: int = 100) -> List[RoleRead]:
        """
        Retrieves a list of roles.

        Args:
            page: The page number to fetch (default: 1).
            per_page: How many items to fetch per page (default: 100).

        Returns:
            A list of roles.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get(self, role_key: str) -> RoleRead:
        """
        Retrieves a role by its key.

        Args:
            role_key: The key of the role.

        Returns:
            The role.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_key(self, role_key: str) -> RoleRead:
        """
        Retrieves a role by its key.
        Alias for the get method.

        Args:
            role_key: The key of the role.

        Returns:
            The role.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_id(self, role_id: str) -> RoleRead:
        """
        Retrieves a role by its ID.
        Alias for the get method.

        Args:
            role_id: The ID of the role.

        Returns:
            The role.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def create(self, role_data: ModelInput[RoleCreate]) -> RoleRead:
        """
        Creates a new role.

        Args:
            role_data: The data for the new role.

        Returns:
            The created role.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def update(self, role_key: str, role_data: ModelInput[RoleUpdate]) -> RoleRead:
        """
        Updates a role.

        Args:
            role_key: The key of the role.
            role_data: The updated data for the role.

        Returns:
            The updated role.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def delete(self, role_key: str) -> None:
        """
        Deletes a role.

        Args:
            role_key: The key of the role to delete.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def assign_permissions(self, role_key: str, permissions: List[str]) -> RoleRead:
        """
        Assigns permissions to a role.

        Args:
            role_key: The key of the role.
            permissions: An array of permission keys (<resourceKey:actionKey>) to be assigned to the role.

        Returns:
            A RoleRead object representing the updated role.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def remove_permissions(self, role_key: str, permissions: List[str]) -> RoleRead:
        """
        Removes permissions from a role.

        Args:
            role_key: The key of the role.
            permissions: An array of permission keys (<resourceKey:actionKey>) to be removed from the role.

        Returns:
            A RoleRead object representing the updated role.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """

class SyncTenantsApi(BasePermitApi):
    def list(self, page: int = 1, per_page: int = 100) -> List[TenantRead]:
        """
        Retrieves a list of tenants.

        Args:
            page: The page number to fetch (default: 1).
            per_page: How many items to fetch per page (default: 100).

        Returns:
            an array of tenants.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def list_tenant_users(self, tenant_key: str, page: int = 1, per_page: int = 100) -> PaginatedResultUserRead:
        """
        Retrieves a list of users for a given tenant.

        Args:
            tenant_key: The key of the tenant.
            page: The page number to fetch (default: 1).
            per_page: How many items to fetch per page (default: 100).

        Returns:
            a PaginatedResultUserRead object containing the list of tenant users.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get(self, tenant_key: str) -> TenantRead:
        """
        Retrieves a tenant by its key.

        Args:
            tenant_key: The key of the tenant.

        Returns:
            the tenant.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_key(self, tenant_key: str) -> TenantRead:
        """
        Retrieves a tenant by its key.
        Alias for the get method.

        Args:
            tenant_key: The key of the tenant.

        Returns:
            the tenant.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_id(self, tenant_id: str) -> TenantRead:
        """
        Retrieves a tenant by its ID.
        Alias for the get method.

        Args:
            tenant_id: The ID of the tenant.

        Returns:
            the tenant.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def create(self, tenant_data: ModelInput[TenantCreate]) -> TenantRead:
        """
        Creates a new tenant.

        Args:
            tenant_data: The data for the new tenant.

        Returns:
            the created tenant.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def update(self, tenant_key: str, tenant_data: ModelInput[TenantUpdate]) -> TenantRead:
        """
        Updates a tenant.

        Args:
            tenant_key: The key of the tenant.
            tenant_data: The updated data for the tenant.

        Returns:
            the updated tenant.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def delete(self, tenant_key: str) -> None:
        """
        Deletes a tenant.

        Args:
            tenant_key: The key of the tenant to delete.

        Returns:
            A promise that resolves when the tenant is deleted.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def delete_tenant_user(self, tenant_key: str, user_key: str) -> None:
        """
        Deletes a user from a given tenant (also removes all roles granted to the user in that tenant).

        Args:
            tenant_key: The key of the tenant from which the user will be deleted.
            user_key: The key of the user to be deleted.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def bulk_create(self, tenants: ModelListInput[TenantCreate]) -> TenantCreateBulkOperationResult:
        """
        Creates tenants in bulk.

        Args:
            tenants: The tenants to create

        Returns:
            the bulk creation report.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def bulk_delete(self, tenants: List[str]) -> TenantDeleteBulkOperationResult:
        """
        Deletes tenants in bulk.

        Args:
            tenants: The tenants identities to delete. Each identity can be either the tenant key or the tenant id.

        Returns:
            the bulk delete report.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """

class SyncUserInvitesApi(BasePermitApi):
    def list(self, page: int = 1, per_page: int = 100) -> PaginatedResultElementsUserInviteRead:
        """
        Retrieves a list of user invites.

        Args:
            page: The page number to retrieve (default: 1).
            per_page: The number of invites per page (default: 100).

        Returns:
            A paginated list of user invites.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get(self, user_invite_id: str) -> ElementsUserInviteRead:
        """
        Retrieves a single user invite by ID.

        Args:
            user_invite_id: The ID of the user invite to retrieve.

        Returns:
            The user invite details.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def create(self, user_invite_data: ModelInput[ElementsUserInviteCreate]) -> ElementsUserInviteRead:
        """
        Creates a new user invite.

        Args:
            user_invite_data: The user invite data to create.

        Returns:
            The created user invite.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def delete(self, user_invite_id: str) -> None:
        """
        Deletes a user invite.

        Args:
            user_invite_id: The ID of the user invite to delete.

        Returns:
            None

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def approve(self, user_invite_id: str, approve_data: ModelInput[ElementsUserInviteApprove]) -> UserRead:
        """
        Approves a user invite.

        Args:
            user_invite_id: The ID of the user invite to approve.
            approve_data: The approval data for the user invite.

        Returns:
            the approved user invite.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """

class SyncUsersApi(BasePermitApi):
    def list(self, page: int = 1, per_page: int = 100) -> PaginatedResultUserRead:
        """
        Retrieves a list of users.

        Args:
            page: The page number to fetch (default: 1).
            per_page: How many items to fetch per page (default: 100).

        Returns:
            a paginated list of users.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get(self, user_key: str) -> UserRead:
        """
        Retrieves a user by its key.

        Args:
            user_key: The key of the user.

        Returns:
            the user object.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_key(self, user_key: str) -> UserRead:
        """
        Retrieves a user by its key.
        Alias for the get method.

        Args:
            user_key: The key of the user.

        Returns:
            the user object.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_by_id(self, user_id: str) -> UserRead:
        """
        Retrieves a user by its ID.
        Alias for the get method.

        Args:
            user_id: The ID of the user.

        Returns:
            the user object.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def create(self, user_data: ModelInput[UserCreate]) -> UserRead:
        """
        Creates a new user.

        Args:
            user_data: The data for the new user.

        Returns:
            the created user.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def update(self, user_key: str, user_data: ModelInput[UserUpdate]) -> UserRead:
        """
        Updates a user.

        Args:
            user_key: The key of the user.
            user_data: The updated data for the user.

        Returns:
            the updated user.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def sync(self, user: _UserSyncInput) -> UserRead:
        """
        Synchronizes user data by creating or updating a user.

        Args:
            user: The data of the user to be synchronized.

        Returns:
            the result of the user creation or update operation.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def delete(self, user_key: str) -> None:
        """
        Deletes a user.

        Args:
            user_key: The key of the user to delete.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def bulk_create(self, users: ModelListInput[UserCreate]) -> UserCreateBulkOperationResult:
        """
        Creates users in bulk.

        Args:
            users: The users to create

        Returns:
            the bulk creation report.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def bulk_replace(self, users: ModelListInput[UserCreate]) -> UserReplaceBulkOperationResult:
        """
        Replaces users in bulk.

        If the user exists - replaces it.
        Otherwise, creates previously non-existing users.

        Args:
            users: The users to replace.

        Returns:
            the bulk replace report.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def bulk_delete(self, users: List[str]) -> UserDeleteBulkOperationResult:
        """
        Deletes users in bulk.

        Args:
            users: The users identities to delete. Each identity can be either the user key or the user id.

        Returns:
            the bulk delete report.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def assign_role(self, assignment: ModelInput[RoleAssignmentCreate]) -> RoleAssignmentRead:
        """
        Assigns a role to a user in the scope of a given tenant.

        Args:
            assignment: The role assignment details.

        Returns:
            the assigned role.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def unassign_role(self, unassignment: ModelInput[RoleAssignmentRemove]) -> None:
        """
        Unassigns a role from a user in the scope of a given tenant.

        Args:
            unassignment: The role unassignment details.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """
    def get_assigned_roles(
        self, user: str, tenant: Optional[str] = None, page: int = 1, per_page: int = 100
    ) -> List[RoleAssignmentRead]:
        """
        Retrieves the roles assigned to a user in a given tenant (if the tenant filter is provided)
        or across all tenants (if the tenant filter is not provided).

        Args:
            user: The key of the user.
            tenant: The key of the tenant.
            page: The page number to fetch.
            per_page: How many items to fetch per page.

        Returns:
            an array of role assignments for the user.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """

class SyncEnforcer:
    def __init__(self, config: PermitConfig): ...
    @property
    def context_store(self) -> ContextStore:
        """
        we let context store be accessed from the outside so that the
        using app can setup a flexible contextual behavior for authorization queries
        """
    def authorized_users(
        self, action: Action, resource: Resource, context: Optional[Context] = None
    ) -> AuthorizedUsersResult:
        """
        Queries to get all the users that are authorized to perform an action on a resource within the specified context.

        Args:
            action: The action to be performed on the resource.
            resource: The resource object representing the resource.
            context: The context object representing the context in which the action is performed. Defaults to None.

        Returns:
            AuthorizedUsersResult: Contains all the authorized users and the role assignments that granted the permission.

        Raises:
            PermitConnectionError: If an error occurs while sending the authorization request to the PDP.

        Examples:

            # all the users that can close any issue?
            await permit.authorized_users('close', 'issue')

            # all the users that can close an issue who's id is 1234?
            await permit.authorized_users('close', 'issue:1234')

            # all the users that can close (any) issues belonging to the 't1' tenant?
            # (in a multi tenant application)
            await permit.authorized_users('close', {'type': 'issue', 'tenant': 't1'})
        """  # noqa: E501
    def bulk_check(self, checks: List[CheckQuery], context: Optional[Context] = None) -> List[bool]:
        """
        Checks if a user is authorized to perform an action on a resource within the specified context.

        Args:
            checks: A list of CheckQuery objects representing the authorization queries to be performed.
                Each check may carry its own ``context``, which is merged over the method-level
                ``context`` for that check only.
            context: The context object representing the context in which the action is performed. Defaults to None.

        Returns:
            list[bool]: A list of booleans indicating whether the user is authorized for each resource.

        Raises:
            PermitConnectionError: If an error occurs while sending the authorization request to the PDP.

        Examples:

            # Bulk query of multiple check conventions
            await permit.bulk_check([
                {
                    "user": user,
                    "action": "close",
                    "resource": {type: "issue", key: "1234"},
                },
                {
                    "user": {key: "user"},
                    "action": "close",
                    "resource": "issue:1235",
                },
                {
                    "user": "user_a",
                    "action": "close",
                    "resource": "issue",
                },
            ])
        """
    def check(self, user: User, action: Action, resource: Resource, context: Optional[Context] = None) -> bool:
        """
        Checks if a user is authorized to perform an action on a resource within the specified context.

        Args:
            user: The user object representing the user.
            action: The action to be performed on the resource.
            resource: The resource object representing the resource.
            context: The context object representing the context in which the action is performed. Defaults to None.

        Returns:
            bool: True if the user is authorized, False otherwise.

        Raises:
            PermitConnectionError: If an error occurs while sending the authorization request to the PDP.

        Examples:

            # can the user close any issue?
            await permit.check(user, 'close', 'issue')

            # can the user close any issue who's id is 1234?
            await permit.check(user, 'close', 'issue:1234')

            # can the user close (any) issues belonging to the 't1' tenant?
            # (in a multi tenant application)
            await permit.check(user, 'close', {'type': 'issue', 'tenant': 't1'})
        """
    def get_user_permissions(
        self,
        user: Union[Dict[str, Any], str],
        tenants: Optional[List[str]] = None,
        resources: Optional[List[str]] = None,
        resource_types: Optional[List[str]] = None,
    ) -> Dict[str, Any]: ...
    def filter_objects(
        self, user: User, action: Action, context: Context, resources: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """Filter the given resources down to the ones the user is allowed to act on.

        Args:
            user: The user object representing the user.
            action: The action to be performed on each resource.
            context: The context every check is evaluated against.
            resources: The resources to filter. Each resource may carry its own ``context``
                key, which is sent as the resource context of that check.

        Returns:
            list[dict]: The subset of ``resources`` the user is authorized for, in input order.
        """

class SyncPdpRoleAssignmentsApi(BasePdpPermitApi):
    def list(
        self,
        user_key: Optional[str] = None,
        role_key: Optional[str] = None,
        tenant_key: Optional[str] = None,
        resource_key: Optional[str] = None,
        resource_instance_key: Optional[str] = None,
        page: int = 1,
        per_page: int = 100,
    ) -> List[RoleAssignment]:
        """
        Retrieves a list of role assignments based on the specified filters.

        Args:
            user_key: optional user filter, will only return role assignments granted to this user.
            role_key: optional role filter, will only return role assignments granting this role.
            tenant_key: optional tenant filter, will only return role assignments granted in that tenant.
            resource_key: optional resource type filter, will only return role assignments granted on that resource type.
            resource_instance_key: optional resource instance filter, will only return role assignments granted on that resource instance.
            page: The page number to fetch (default: 1).
            per_page: How many items to fetch per page (default: 100).

        Returns:
            an array of role assignments.

        Raises:
            PermitApiError: If the API returns an error HTTP status code.
            PermitContextError: If the configured ApiContext does not match the required endpoint context.
        """  # noqa: E501
