"""Generate permit/_sync_types.pyi, the type checkers' view of the SDK's blocking classes.

The blocking classes (``permit.sync.Permit().api.users`` and the rest) are empty
subclasses of the async classes whose ``SyncClass`` metaclass swaps every public
coroutine method for a blocking wrapper when the class is created. Type checkers cannot
follow that and would type every blocking call as returning a coroutine. The stub
declares each converted method as a plain ``def`` with the async method's signature and
docstring, and the runtime modules import it under ``TYPE_CHECKING``.

A stub class subclasses the async class's bases rather than the async class itself,
because a ``def`` overriding an ``async def`` is an incompatible override.

Run ``make generate-sync-stubs`` after changing an async class. tests/test_typing_surface.py
fails while the committed stub differs from what this script generates.
"""

import ast
import builtins
import importlib
import importlib.util
import inspect
import pkgutil
import sys
from collections import defaultdict
from pathlib import Path

import permit
from permit.utils.sync import SYNC_WRAPPER_MARKER, SyncClass, iscoroutine_func

REPO_ROOT = Path(__file__).resolve().parents[1]
STUB_PATH = REPO_ROOT / "permit" / "_sync_types.pyi"
LINE_LENGTH = 120
INDENT = "    "

# The stub is a single namespace, so runtime classes that share a name need distinct stub names.
STUB_NAMES = {"permit.pdp_api.pdp_api_client.SyncRoleAssignmentsApi": "SyncPdpRoleAssignmentsApi"}
# Kept in the stub: they change how type checkers see the member.
TYPING_DECORATORS = {"overload", "property", "staticmethod", "classmethod"}
# Dropped from the stub: they wrap the method without changing its signature.
TRANSPARENT_DECORATORS = {"validate_arguments", "deprecated"}

HEADER = """\
# Generated by scripts/generate_sync_stubs.py from the async classes. Do not edit;
# run `make generate-sync-stubs` instead."""


class StubError(Exception):
    """An async class uses a construct the generator cannot express in the stub."""


def qualified_name(cls: type) -> str:
    return f"{cls.__module__}.{cls.__qualname__}"


def stub_name(cls: type) -> str:
    return STUB_NAMES.get(qualified_name(cls), cls.__name__)


def introduces_sync_class(value: object) -> bool:
    """Whether ``value`` is a class declared with ``metaclass=SyncClass``.

    Subclasses of such a class inherit the metaclass (``SyncPermitApiClient`` does), but
    they are ordinary classes whose own source type checkers can read.
    """
    return isinstance(value, SyncClass) and not any(isinstance(base, SyncClass) for base in value.__bases__)


def sync_classes() -> list[type]:
    """Every class declared with ``metaclass=SyncClass``, ordered by qualified name."""
    found: dict[str, type] = {}
    for info in pkgutil.walk_packages(permit.__path__, "permit."):
        module = importlib.import_module(info.name)
        for value in vars(module).values():
            if introduces_sync_class(value) and value.__module__ == info.name:
                found[qualified_name(value)] = value
    names = [stub_name(cls) for cls in found.values()]
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        raise StubError(f"Stub class names collide: {duplicates}. Add an entry to STUB_NAMES.")
    return [found[key] for key in sorted(found)]


def module_tree(module_name: str) -> tuple[str, ast.Module]:
    source = Path(inspect.getfile(sys.modules[module_name])).read_text()
    return source, ast.parse(source)


def class_node(tree: ast.Module, name: str) -> ast.ClassDef:
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == name:
            return node
    raise StubError(f"class {name} not found in its module's source")


def type_checking_statements(tree: ast.Module) -> list[ast.stmt]:
    """Top-level statements as a type checker reads them: ``if TYPE_CHECKING`` bodies inlined."""
    statements: list[ast.stmt] = []
    for node in tree.body:
        if isinstance(node, ast.If) and "TYPE_CHECKING" in ast.unparse(node.test):
            statements.extend(node.body)
        else:
            statements.append(node)
    return statements


def converted_names(sync_cls: type) -> set[str]:
    return {
        name
        for name in dir(sync_cls)
        if not name.startswith("_") and getattr(getattr(sync_cls, name), SYNC_WRAPPER_MARKER, False)
    }


def async_class(sync_cls: type) -> type:
    """The async class a sync class converts, checking the shape the generator relies on."""
    if len(sync_cls.__bases__) != 1:
        raise StubError(f"{qualified_name(sync_cls)} must have exactly one base, the async class")
    (async_cls,) = sync_cls.__bases__
    _, tree = module_tree(sync_cls.__module__)
    body = class_node(tree, sync_cls.__name__).body
    if not all(isinstance(node, ast.Pass) for node in body):
        raise StubError(f"{qualified_name(sync_cls)} must have an empty body; the stub only mirrors its async base")
    for base in async_cls.__bases__:
        coroutines = sorted(
            name for name in dir(base) if not name.startswith("_") and iscoroutine_func(getattr(base, name))
        )
        if coroutines:
            raise StubError(f"{qualified_name(base)} has public coroutine methods {coroutines}; the stub subclasses it")
    return async_cls


def is_simple_default(node: ast.expr) -> bool:
    if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
        node = node.operand
    return isinstance(node, ast.Constant) and not isinstance(node.value, bytes)


def stub_default(node: ast.expr) -> str:
    return ast.unparse(node) if is_simple_default(node) else "..."


def parameter(arg: ast.arg, default: ast.expr | None, prefix: str = "") -> str:
    text = prefix + arg.arg
    if arg.annotation is not None:
        text += f": {ast.unparse(arg.annotation)}"
        if default is not None:
            text += f" = {stub_default(default)}"
    elif default is not None:
        text += f"={stub_default(default)}"
    return text


def parameters(args: ast.arguments) -> list[str]:
    positional = args.posonlyargs + args.args
    defaults: list[ast.expr | None] = [None] * (len(positional) - len(args.defaults)) + list(args.defaults)
    parts = [parameter(arg, default) for arg, default in zip(positional, defaults, strict=True)]
    if args.posonlyargs:
        parts.insert(len(args.posonlyargs), "/")
    if args.vararg is not None:
        parts.append(parameter(args.vararg, None, "*"))
    elif args.kwonlyargs:
        parts.append("*")
    parts.extend(parameter(arg, default) for arg, default in zip(args.kwonlyargs, args.kw_defaults, strict=True))
    if args.kwarg is not None:
        parts.append(parameter(args.kwarg, None, "**"))
    return parts


def signature_lines(head: str, params: list[str], tail: str, indent: str) -> list[str]:
    """Lay out ``head(params)tail`` the way ruff format does at LINE_LENGTH."""
    one_line = f"{indent}{head}({', '.join(params)}){tail}"
    if len(one_line) <= LINE_LENGTH:
        return [one_line]
    inner = indent + INDENT
    joined = f"{inner}{', '.join(params)}"
    if len(joined) <= LINE_LENGTH:
        return [f"{indent}{head}(", joined, f"{indent}){tail}"]
    return [f"{indent}{head}(", *(f"{inner}{param}," for param in params), f"{indent}){tail}"]


def docstring_lines(node: ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef, source: str, indent: str) -> list[str]:
    if ast.get_docstring(node, clean=False) is None:
        return []
    expr = node.body[0]
    if expr.col_offset != len(indent):
        raise StubError(f"docstring of {node.name} is not indented {len(indent)} spaces")
    segment = ast.get_source_segment(source, expr)
    if segment is None or expr.end_lineno is None or expr.end_col_offset is None:
        raise StubError(f"cannot read the docstring source of {node.name}")
    # Keep a trailing comment: a noqa directive there covers every line of the docstring.
    last_line = source.splitlines()[expr.end_lineno - 1].encode()
    trailing = last_line[expr.end_col_offset :].decode().strip()
    comment = f"  {trailing}" if trailing.startswith("#") else ""
    return [indent + segment + comment]


def decorator_name(node: ast.expr) -> str:
    target = node.func if isinstance(node, ast.Call) else node
    return ast.unparse(target)


def function_lines(node: ast.FunctionDef | ast.AsyncFunctionDef, source: str) -> list[str]:
    lines = []
    for decorator in node.decorator_list:
        name = decorator_name(decorator)
        if name in TYPING_DECORATORS or name.endswith(".setter"):
            lines.append(f"{INDENT}@{ast.unparse(decorator)}")
        elif name not in TRANSPARENT_DECORATORS:
            raise StubError(f"{node.name}: unknown decorator @{name}; classify it in the generator")
    tail = f" -> {ast.unparse(node.returns)}:" if node.returns is not None else ":"
    body_indent = INDENT * 2
    docstring = docstring_lines(node, source, body_indent)
    if not docstring:
        tail += " ..."
    lines.extend(signature_lines(f"def {node.name}", parameters(node.args), tail, INDENT))
    lines.extend(docstring)
    return lines


def annotation_nodes(node: ast.FunctionDef | ast.AsyncFunctionDef) -> list[ast.expr]:
    args = node.args
    every_arg = args.posonlyargs + args.args + args.kwonlyargs + [a for a in (args.vararg, args.kwarg) if a]
    nodes = [arg.annotation for arg in every_arg if arg.annotation is not None]
    if node.returns is not None:
        nodes.append(node.returns)
    nodes.extend(
        decorator
        for decorator in node.decorator_list
        if decorator_name(decorator) in TYPING_DECORATORS or decorator_name(decorator).endswith(".setter")
    )
    return nodes


def referenced_names(nodes: list[ast.expr]) -> set[str]:
    names: set[str] = set()
    for root in nodes:
        for node in ast.walk(root):
            if isinstance(node, ast.Name):
                names.add(node.id)
            elif isinstance(node, ast.Constant) and isinstance(node.value, str):
                raise StubError(f"string annotation {node.value!r} is not supported; use the name directly")
    return names


def resolve(module_name: str, tree: ast.Module, name: str) -> tuple[str, str] | None:
    """Where a type checker finds ``name`` as used in ``module_name``: (module, attribute), or None for a builtin."""
    package = module_name.rpartition(".")[0]
    for node in type_checking_statements(tree):
        if isinstance(node, ast.ImportFrom):
            for alias in node.names:
                if (alias.asname or alias.name) == name:
                    source = importlib.util.resolve_name("." * node.level + (node.module or ""), package)
                    return source, alias.name
        elif isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == name:
            return module_name, name
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            if any(isinstance(target, ast.Name) and target.id == name for target in targets):
                return module_name, name
    if hasattr(builtins, name):
        return None
    raise StubError(f"cannot find where {module_name} gets {name!r}")


def member_sort_key(name: str) -> tuple[int, str]:
    """isort's order-by-type: constants, then classes, then everything else."""
    if name.isupper() and len(name) > 1:
        return 0, name
    if name[0].isupper():
        return 1, name
    return 2, name


def import_block(imports: dict[str, set[str]]) -> str:
    """``from module import names`` lines, grouped and ordered the way ruff's isort rules want."""
    sections: dict[int, list[str]] = defaultdict(list)
    for module in sorted(imports):
        top = module.partition(".")[0]
        section = 0 if top in sys.stdlib_module_names else 2 if top == "permit" else 1
        names = sorted(imports[module], key=member_sort_key)
        line = f"from {module} import {', '.join(names)}"
        if len(line) <= LINE_LENGTH:
            sections[section].append(line)
        else:
            sections[section].append(f"from {module} import (\n" + "".join(f"{INDENT}{n},\n" for n in names) + ")")
    return "\n\n".join("\n".join(sections[key]) for key in sorted(sections))


def class_lines(sync_cls: type, imports: dict[str, set[str]]) -> list[str]:
    async_cls = async_class(sync_cls)
    source, tree = module_tree(async_cls.__module__)
    node = class_node(tree, async_cls.__name__)
    converted = converted_names(sync_cls)
    emitted: set[str] = set()
    body: list[str] = docstring_lines(node, source, INDENT)
    annotations: list[ast.expr] = []
    for member in node.body:
        if isinstance(member, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if member.name.startswith("_") and member.name != "__init__":
                continue
            body.extend(function_lines(member, source))
            annotations.extend(annotation_nodes(member))
            emitted.add(member.name)
        elif isinstance(member, (ast.Assign, ast.AnnAssign)):
            targets = member.targets if isinstance(member, ast.Assign) else [member.target]
            public = [ast.unparse(t) for t in targets if not ast.unparse(t).startswith("_")]
            if public:
                raise StubError(f"{async_cls.__name__} has class attributes {public}; teach the generator to copy them")
    missing = sorted(converted - emitted)
    if missing:
        raise StubError(f"{qualified_name(sync_cls)} converts {missing}, which {async_cls.__name__} does not define")

    bases = []
    for base in async_cls.__bases__:
        if base is not object:
            bases.append(base.__name__)
            imports[base.__module__].add(base.__name__)
    for name in sorted(referenced_names(annotations)):
        location = resolve(async_cls.__module__, tree, name)
        if location is not None:
            imports[location[0]].add(location[1])

    head = f"class {stub_name(sync_cls)}({', '.join(bases)}):" if bases else f"class {stub_name(sync_cls)}:"
    return [head, *(body or [f"{INDENT}..."])]


def render_stub() -> str:
    """The full text of permit/_sync_types.pyi for the SDK as currently defined."""
    imported_from = Path(permit.__file__).resolve().parent
    if imported_from != STUB_PATH.parent:
        msg = f"imported permit from {imported_from}, not {STUB_PATH.parent}; run with PYTHONPATH={REPO_ROOT}"
        raise StubError(msg)
    imports: dict[str, set[str]] = defaultdict(set)
    classes = [class_lines(sync_cls, imports) for sync_cls in sync_classes()]
    parts = [HEADER, import_block(imports)]
    parts.extend("\n".join(lines) for lines in classes)
    return "\n\n".join(parts) + "\n"


def main() -> None:
    STUB_PATH.write_text(render_stub())


if __name__ == "__main__":
    main()
