name: Release permit python SDK

on:   
  release:
    # job will automatically run after a new "release" is create on github.
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: []


jobs:
  build-n-publish:
    name: Build and publish permit python SDK to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install python deps
      run: >-
        python -m pip install build twine wheel --user
    - name: Build & Publish SDK
      run: >-
        make publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
